nck/readers/adobe_reader.py
- Adding "source":"warehouse" to reportDescription, so that we can access multiple pages
- Adding docstrings to AdobeReader methods, and some links to Adobe documentation
=> Fix: requesting Data Warehouse reports to access multiple pages

.gitignore, Makefile, requirements-dev.txt
- add `Pipfile*` to `.gitignore` so that developpers can use Pipenv
- add recursive import of `requirements.txt` inside `requirements-dev.txt` so that all dependencies for developing can be installed in one line
- This PR does not need tests.
=> Update project config

nck/readers/adobe_reader.py, nck/readers/googleads_reader.py, nck/readers/sa360_reader.py, nck/utils/text.py, tests/test_main_method.py, tests/utils/test_text_utils.py
Current behavior: the "total" row is processed in csv files
Expected behavior: No "total" in output
=> don't process total line in csv files

requirements.txt
=> test3 auto publish NCK v1.0

.github/workflows/buildtogcp.yml
=> test4 auto publish NCK v1.0

README.md, nck/clients/adobe_client.py, nck/helpers/adobe_helper_2_0.py, nck/readers/README.md, nck/readers/__init__.py, nck/readers/adobe_reader_2_0.py, requirements.txt, tests/readers/test_adobe_reader_2_0.py
Note: while Data Warehouse reports won't be made available in API 2.0, Adobe Analytics Reader 1.4 will be maintained, so that we can handle multiple-dimension reports with an efficient processing time.
=> Adobe Reader 2.0

.env, nck/readers/adobe_reader_2_0.py
Replacing the "adobe" suffix by "adobe_2_0" in AdobeReader 2.0 for Berlioz compatibility
=> Modifying AdobeReader 2.0 argument names

nck/helpers/twitter_helper.py, nck/readers/README.md, nck/readers/twitter_reader.py, tests/readers/test_twitter_reader.py
**Adding a new entity option "CARD" applicable to the "ENTITY" report type**
Twitter Cards are sort of creative containers, having a "website_dest_url" attribute.
This attribute will allow us to match Twitter Ads data with Analytics data through the CID parameter.
=> Twitter: requesting Cards

nck/readers/dv360_reader.py
=> refacto: format docstrings

nck/readers/dv360_reader.py
=> refacto: take benoit's comments into account

nck/writers/local_writer.py, nck/writers/s3_writer.py
=> S3 write : log the path where the file is written to.

nck/helpers/dbm_helper.py, nck/readers/README.md, nck/readers/dbm_reader.py, nck/utils/exceptions.py
=> upgrade DBM v1.1 - update get_query and remove sdf requests

nck/readers/dbm_reader.py, tests/readers/test_dbm_reader.py
- Remove TOTALS row in DBM_Reader
=> remove TOTALS row in DBM_Reader

docs/source/readers.rst, nck/helpers/mytarget_helper.py, nck/readers/mytarget_reader.py
=> Improve mytarget connector

nck/readers/mytarget_reader.py
=> fix: adjust click args

nck/readers/mytarget_reader.py, nck/utils/exceptions.py
=> fix: update mytarget

nck/readers/dv360_reader.py
=> fix: rmv typo in decorator

nck/config.py, nck/readers/dv360_reader.py, nck/utils/stdout_to_log.py
=> discovery Log enabled in debug mode

nck/readers/googleads_reader.py
Hotfix logs googleads:
- remove duplicates in logs
- fix error message
- global formatting
=> Vm hotfix log googleads

nck/helpers/mytarget_helper.py, nck/readers/mytarget_reader.py
The goal here was to add the status and date of campaigns for budget reports.
Also make start/end dates uniform whether they are retrieved from a date range or not. (Click seemed to have no date option, datetime only and the util function send a date)
=> Add data budget

nck/readers/mytarget_reader.py
Just a typo which occured in the last change made.
=> fix: edit typo in last minute change

nck/writers/gcs_writer.py, nck/writers/objectstorage_writer.py, nck/writers/s3_writer.py, requirements-dev.txt, tests/writers/test_s3_writer.py
=> Storage writers factorization

ack/readers/twitter/reader.py, ack/writers/amazon_s3/writer.py, ack/writers/object_storage/writer.py
This PR try to solve the problem encountered by @bibimorlet by removing the retry in gcs writer.
=> Hotfix   gcs writter

ack/readers/twitter/reader.py
- Adds logical retries in order to handle Twitter RateLimits
=> fix Twitter RateLimit

.env
Change Docker tag version to v2.0 to match upcoming release
=> Feat: change docker tag version
