artefactory/artefactory-connectors-kit

nck/readers/adobe_reader.py

Handles the case when no data is returned by Adobe Reporting API 1.4:

Fix: handling empty reports

---

requirements.txt

Used for AdobeReader 2.0 JWT authentication

Adding cryptography to requirements.txt

---

nck/helpers/adobe_helper.py
nck/helpers/adobe_helper_2_0.py
nck/readers/README.md
nck/readers/adobe_reader.py
nck/readers/adobe_reader_2_0.py
tests/readers/test_adobe_reader.py

Moving from WSSE to JWT authentication (that we are already using with Adobe Reader 2.0), as WSSE is now deprecated.

Adobe Reader 1.4: moving from WSSE to JWT auth

---

nck/helpers/facebook_helper.py
nck/readers/README.md
nck/readers/facebook_reader.py
tests/readers/test_facebook_reader.py

A lot of API calls are made during Ad Management queries.
Here is the process that we currently follow if we want to get configuration info on AdCreatives (for instance): 
- Step 1 - We get all AdCreative objects under the account (= 1 API call)
- Step 2 - For each AdCreative object, we make 1 API call to get the requested fields
It has 2 downsides:
- In terms of processing time, it is very slow.
- If we are not vigilant, API rate limit can be reached.
I implemented batch requests (of 50 items) to the Ad Management endpoint.
- With this set-up, Facebook API can parallelize requests, making our connector much more efficient (17 seconds for 1,000 requests vs. 1min30 previously).
- Also, it gives us access to response headers, allowing us to put the program on sleep if we are too close to …

Facebook Reader : Batch Requests on Ad Management queries

---

nck/readers/ga_reader.py
requirements-dev.txt
tests/readers/test_ga_reader.py

- Streams generated by the GA reader did not contain any informations about the requested view ID.
- Added a Click flag "--ga-add-view" to be able to add the requested view ID in each row of the stream. 
- Added a test_format_data_and_view_id method to test the addition of the field "viewId" in the GaStream.

Added flag to add viewId optionally

---

nck/readers/googleads_reader.py

**Context**
If a GoogleAds account reaches 15 months without spend, it is cancelled (but your client can still reactivate it following Google guidelines on [this link](https://support.google.com/google-ads/answer/2375392?hl=en)). As a consequence, if you try to request a report from this account, the API call will raise an exception.
**Previous behavior**
If one of the GoogleAds accounts involved in the request is cancelled, the whole NCK command crashes.
**New behavior**
If one of the GoogleAds accounts involved in the request is cancelled, it is skipped and the NCK command continues to run.

GoogleAds: skipping inactive clientCustomerIds

---

.dockerignore

fix #34 
Add `.dockerignore` in order to reduce image size and build time.
No need for tests as there is no code linked to this PR.
This is not for end users and it does not impact contributions directly, so there is no documentation attached to this PR.

Feat: add .dockerignore

---

setup.py

Build failed. See the [logs](https://github.com/artefactory/nautilus-connectors-kit/runs/1057021760).
The README file was needed in order to get package documentation. As NCK is mostly used as a Docker image, this documentation is not useful. It is already in the README.

fix: remove commented code and unused variables

---

nck/readers/gs_reader.py

A lot of "Spreadsheet not found" errors occured when the Google Sheet was not in the "My Drive" section.
More robust method to get the spreadsheet thanks its key rather than its name. Thus we are sure that the key is unique and there is no path issues.

fix: get spreadsheet thank to key rather than name

---

nck/readers/gs_reader.py

Gsheet reader output file did not have a meaningful name and contained whitespaces that might cause errors.
Change first part of the name with _gsheet_

fix: better output file name with gsheet reader

---

requirements.txt

- Facebook Business API v5.0 deprecated: API calls don't work since 2020-09-28

upgrade facebook-business to v8.0.4

---

README.md
nck/helpers/confluence_helper.py
nck/readers/README.md
nck/readers/__init__.py
nck/readers/confluence_reader.py
requirements.txt
tests/helpers/test_confluence_helper.py
tests/readers/test_confluence_reader.py

- Adding **a new Confluence Reader** (requested by Benoit Robin). The primary purpose of this connector is to get an overview of the pages available on Smartefact (title, link, associated labels, etc.).
- To meet Benoit's needs, I had to **create custom fields that are parsing the HTML body of Smartefact pages** (for instance, the `client_completion` field checks if mandatory template sections have been filled by users or not). It makes API response parsing a bit more complex than usually, but I tried to make it as smooth as possible.
This PR adds tests.
This PR adds documentation.

Feat: adding Confluence Reader

---

nck/helpers/facebook_helper.py
nck/readers/README.md
nck/readers/facebook_reader.py
requirements.txt
tests/helpers/test_api_client_helper.py
tests/readers/test_facebook_reader.py
tests/readers/test_yandex_statistics_reader.py

_All below updates are backward-compatible._
- **[Solved]** If a field value was not a string, if was not returned by the Facebook reader
- **[Solved]** If a field value was a list dictionaries, but not following an action breakdown pattern (= at least one key in each dictionary starts with "action_"), it made the Facebook reader crash
- The Facebook reader now handles the Pixel level for Ad Management queries.
- The Facebook reader now allows you to explore fields content: the API call can be completed, even if you don't know exactly what the field values you're requesting look like (if they are strings, dictionaries, lists of dictionaries, Facebook objects, etc.). The Facebook reader will simply return the "raw" field value as a string, so that you can adjust your query.
Illustration …

Fix/Enh: a few fixes/enhancements to the Facebook reader

---

nck/writers/local_writer.py

Add a file_name parameter to the local_writer in order to:
- Choose destination file name if needed
- Handle "File Name Too Long" Error
+: Add single-letter arguments to simplify debug commands. To discuss

add file_name parameter - local_writer

---

.env
nck/readers/facebook_reader.py

- Ads Insights request are now asynchronous.
- Handles requests of bigger reports --> avoids the "Error 500: Please reduce the amount of data you're asking"
- Handles requests of more than 1 or 2 days of data --> Faster History requests
1) Query ads_insights report on Facebook Marketing API
- retries: 3.
2) Wait for 100% completion of the report:
- Wait for the report to be complete
- retries: Exponential retries between 5s and 5min
- Timeout: 40min
3) Wait for job to be complete:
- Wait for "Job Completed"
--> because the API sends during a brief period of time "Job Running" and "100%" together.
- retries: exponential retries between 10s and 1min
- Timeout: 5min
- During 2), Facebook API sometimes fails or queries report indefinitely. (especially when reports are way too voluminous)
- …

Facebook Reader: asynchronous requests

---

nck/helpers/confluence_helper.py
tests/helpers/test_confluence_helper.py

Minor enhancement.
Adding "Salesforce ID" to the list of client properties that should be collected from Client pages HTML body.

Feat: add "Salesforce ID" to client properties

---

nck/utils/file_reader.py

fix: raise csv field limit value to 1 000 000

---

nck/entrypoint.py
nck/readers/reader.py

In fact, some readers return normalized streams. They should return non-normalized streams.
Retrieve --normalize-keys at entrypoint in order to normalize the output JSONstreams if needed.
**Example:**
```
python nck/entrypoint/py --normalize-keys true <reader> [...] <writer>
```
=> if `<reader>` initially returns a JSONStream, the stream will be changed in a NormalizedJSONStream

add normalize-keys at entrypoint

---

nck/entrypoint.py

IMPORTANT NOTE: There is an issue with the entrypoint which is more general and who might need a small fix. When generating the list of provided readers and writers in the entrypoint.py file instances are created in the isinstance(cmd(), Reader/Writer). This causes 3 initiations of our classes instead of one which can lead to issues or useless logs. Maybe using class variables instead of Reader/Writer objects would be better to retrieve the correct cmds. Is there a specific reason why it is how it is today or can we fix this later ? @bibimorlet @gabrielleberanger @benoitgoujon

fix: edit reader/writer instanciation

---

nck/entrypoint.py

Adding validation of provided readers and writers again in the `nck/entrypoint.py` module(it had been removed by mistake when fixing command instantiation earlier this week).

Fix: add missing command validation

---

nck/readers/gcs_reader.py
nck/readers/objectstorage_reader.py
nck/readers/s3_reader.py
nck/utils/file_reader.py
tests/readers/test_objectstorage_reader.py

-  #removed broken and useless code in `nck/readers/objectstorage_reader.py`, 
- Created njson reader in `nck/utils/file_reader.py`
- Moved reader factory from `nck/readers/objectstorage_reader.py` to `nck/utils/file_reader` .

fix : corrected unworking storageobject_reader

---

requirements.txt

Twitter Ads API v7 will stop working on March 2nd: therefore, I upgraded our requirements to Twitter Ads API v8. The API upgrade does not impact any of the reports we are currently using (FYI, you can find the list of changes [on this page](https://twittercommunity.com/t/ads-api-version-8/141914?utm_campaign=ADS_PU_GBL_EN_v7%20Sunset_Reminder%203_210225&utm_medium=email&utm_source=Eloqua&ref=)).

Enh: upgrade Twitter Ads API version

---

nck/utils/file_reader.py

Just adapt the name of the function according to the recent edits. The new name was just not applied to sdf_to_nsjon...
Interrogation about a possible improvement:
Makes me think about something, what about including checks in CI to test the full pipeline ? I know it will take time but maybe it would only be necessary to merge from dev to a new "master/main" branch. I haven't thought about all the details about this kind CI checks but it could avoid us using version of NCK in which don't work... I had to made test manually and correct these to make sure the new NCK we're going to use would work, I think this kind of feature could be an interesting improvement.
If you guys agree and if you think this is doable I will write a new issue.

fix: adapt new func names

---

docs/source/getting_started.rst
docs/source/readers.rst
nck/readers/confluence_reader.py
nck/readers/dcm_reader.py
nck/readers/facebook_reader.py
nck/readers/ga_reader.py
nck/readers/googleads_reader.py
nck/readers/gsheets_reader.py
nck/readers/mysql_reader.py
nck/readers/objectstorage_reader.py
nck/readers/radarly_reader.py
nck/readers/sa360_reader.py
nck/readers/salesforce_reader.py
nck/readers/search_console_reader.py
nck/readers/ttd_reader.py
nck/utils/text.py
tests/readers/test_ga_reader.py
tests/readers/test_ttd.py

:heavy_exclamation_mark: **If we merge this PR into dev, you will need to slightly update the commands you are sending to NCK. Please read carefully the below description to warn me if these changes cannot be easily implemented in the context of your project.**
This PR addresses Issue #103.
Two methods were coexisting to normalize field names. By normalizing, I mean replacing any special character or white space by an underscore, to match destination requirements (e.g. BigQuery that only accepts field names containing letters, digits or underscores).
These 2 methods are detailed below:
- Field names could be normalized **at the click group level**, with the click option `--normalize-keys`:
```
python nck/entrypoint.py --normalize-keys true <READER_COMMAND> <WRITER_COMMAND>
```
- Field …

Enh: standardize field name normalization

---

nck/readers/dbm_reader.py
nck/utils/date_handler.py
nck/utils/exceptions.py
tests/utils/test_date_handler.py

Date checks were inconsistent with the reader.
The reader was no longer usable with (start-end, end-date) couple parameters.

fix date checks and format them

---

.pre-commit-config.yaml
nck/readers/adobe_reader_2_0.py
nck/readers/dcm_reader.py
nck/readers/mytarget_reader.py
nck/readers/sa360_reader.py
nck/readers/search_console_reader.py
nck/readers/ttd_reader.py
nck/readers/twitter_reader.py
nck/utils/date_handler.py
tests/readers/test_adobe_reader_2_0.py
tests/readers/test_search_console_reader.py
tests/readers/test_ttd.py
tests/readers/test_twitter_reader.py
tests/utils/test_date_handler.py

- My PR addresses the following Issue: #96 
- add a build_date_range function in `nck/utils/date_handler.py` to manage optional date range when needed in a reader
- modify `nck/readers/adobe_reader_2_0.py` to use this new function instead of a built-in one
- add tests for this new function and adapt an existing test for adobe reader 2.0
My PR adds the following unit tests:
- `nck/utils/test_date_handler.py` create `test_build_date_range_without_dates` to test the build_data_range function only with a date range
- `nck/utils/test_date_handler.py` create `test_build_date_range_with_dates` to test the build_data_range function only with dates
- `nck/readers/test_adobe_reader_2_0.py:` modify `test_build_date_range` to `test_format_date_range` after changing the function

Predefined date range option
